// components/admin/BlogPostList.vue
<template>
  <div>
    <p v-if="loading" style="color: var(--text-muted)">Laden...</p>
    <p v-else-if="error" style="color: #ff6b6b">{{ error }}</p>
    <template v-else>
      <div class="list-header">
        <span class="count">{{ posts.length }} post{{ posts.length !== 1 ? 's' : '' }}</span>
        <NuxtLink to="/admin/blog/new" class="new-btn">+ Nieuw artikel</NuxtLink>
      </div>

      <div v-if="posts.length === 0" class="empty">
        <p>Nog geen blogposts. Maak je eerste aan!</p>
      </div>

      <table v-else class="table">
        <thead>
          <tr>
            <th class="th">Titel</th>
            <th class="th">Locale</th>
            <th class="th">Status</th>
            <th class="th">Datum</th>
            <th class="th th-right">Acties</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="post in posts" :key="post.id" class="tr">
            <td class="td">
              <span class="title-text">{{ post.title }}</span>
              <span class="slug">/{{ post.slug }}</span>
            </td>
            <td class="td">
              <span class="locale-badge">{{ post.locale.toUpperCase() }}</span>
            </td>
            <td class="td">
              <span :class="post.published ? 'status-published' : 'status-draft'">
                {{ post.published ? 'Gepubliceerd' : 'Concept' }}
              </span>
            </td>
            <td class="td">
              <span class="date">{{ formatDate(post.publishedAt || post.createdAt) }}</span>
            </td>
            <td class="td td-right">
              <div class="actions">
                <NuxtLink :to="`/admin/blog/${post.id}/edit`" class="action-btn">Bewerken</NuxtLink>
                <button class="action-btn" @click="togglePublish(post)">
                  {{ post.published ? 'Depubliceren' : 'Publiceren' }}
                </button>
                <button class="delete-btn" @click="deletePost(post)">Verwijderen</button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </template>
  </div>
</template>

<script setup lang="ts">
interface Post {
  id: string;
  slug: string;
  locale: string;
  title: string;
  description: string;
  author: string;
  tags: string[];
  published: boolean;
  publishedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

const posts = ref<Post[]>([]);
const loading = ref(true);
const error = ref('');

onMounted(() => fetchPosts());

async function fetchPosts() {
  loading.value = true;
  error.value = '';
  try {
    posts.value = await $fetch<Post[]>('/api/blog');
  } catch (err: any) {
    error.value = err.data?.message || err.message || 'Failed to fetch posts';
  } finally {
    loading.value = false;
  }
}

async function togglePublish(post: Post) {
  try {
    await $fetch(`/api/blog/${post.id}`, {
      method: 'PUT',
      body: { published: !post.published },
    });
    await fetchPosts();
  } catch (err: any) {
    alert(err.data?.message || err.message);
  }
}

async function deletePost(post: Post) {
  if (!confirm(`Weet je zeker dat je "${post.title}" wilt verwijderen?`)) return;
  try {
    await $fetch(`/api/blog/${post.id}`, { method: 'DELETE' });
    await fetchPosts();
  } catch (err: any) {
    alert(err.data?.message || err.message);
  }
}

function formatDate(dateStr: string | null) {
  if (!dateStr) return '–';
  return new Date(dateStr).toLocaleDateString('nl-NL', {
    year: 'numeric', month: 'short', day: 'numeric',
  });
}
</script>

<style scoped>
.list-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 24px;
}

.count { font-size: 0.85rem; color: var(--text-muted); }

.new-btn {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 8px 16px;
  background: var(--accent);
  color: var(--bg-deep);
  font-weight: 600;
  font-size: 0.85rem;
  border-radius: 6px;
  text-decoration: none;
}

.empty {
  text-align: center;
  padding: 60px 0;
  color: var(--text-muted);
}

.table {
  width: 100%;
  border-collapse: collapse;
}

.th {
  text-align: left;
  padding: 10px 12px;
  font-size: 0.75rem;
  font-weight: 600;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
  border-bottom: 1px solid var(--border-glass);
}

.th-right { text-align: right; }

.tr { border-bottom: 1px solid rgba(255, 255, 255, 0.04); }

.td {
  padding: 14px 12px;
  font-size: 0.9rem;
  vertical-align: middle;
}

.td-right { text-align: right; }

.title-text {
  display: block;
  font-weight: 500;
  color: var(--text-primary);
}

.slug {
  display: block;
  font-size: 0.75rem;
  color: var(--text-muted);
  margin-top: 2px;
}

.locale-badge {
  font-size: 0.75rem;
  font-weight: 600;
  padding: 2px 6px;
  background: rgba(255, 255, 255, 0.06);
  border-radius: 4px;
  color: var(--text-secondary);
}

.status-published {
  font-size: 0.8rem;
  font-weight: 500;
  color: var(--accent);
}

.status-draft {
  font-size: 0.8rem;
  font-weight: 500;
  color: var(--text-muted);
}

.date {
  font-size: 0.85rem;
  color: var(--text-secondary);
}

.actions {
  display: flex;
  gap: 8px;
  justify-content: flex-end;
}

.action-btn {
  padding: 5px 10px;
  font-size: 0.8rem;
  background: rgba(255, 255, 255, 0.04);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 4px;
  color: var(--text-secondary);
  cursor: pointer;
  text-decoration: none;
  transition: border-color 0.2s;
}

.action-btn:hover {
  border-color: rgba(255, 255, 255, 0.16);
}

.delete-btn {
  padding: 5px 10px;
  font-size: 0.8rem;
  background: rgba(255, 59, 48, 0.08);
  border: 1px solid rgba(255, 59, 48, 0.15);
  border-radius: 4px;
  color: #ff6b6b;
  cursor: pointer;
}
</style>

// site/src/components/admin/BlogPostList.tsx
import { useState, useEffect } from 'react';

interface Post {
  id: string;
  slug: string;
  locale: string;
  title: string;
  description: string;
  author: string;
  tags: string[];
  published: boolean;
  publishedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export default function BlogPostList() {
  const [posts, setPosts] = useState<Post[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    fetchPosts();
  }, []);

  async function fetchPosts() {
    try {
      const res = await fetch('/api/blog');
      if (!res.ok) throw new Error('Failed to fetch posts');
      const data = await res.json();
      setPosts(data);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  async function togglePublish(post: Post) {
    try {
      const res = await fetch(`/api/blog/${post.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ published: !post.published }),
      });
      if (!res.ok) throw new Error('Failed to update post');
      await fetchPosts();
    } catch (err: any) {
      alert(err.message);
    }
  }

  async function deletePost(post: Post) {
    if (!confirm(`Weet je zeker dat je "${post.title}" wilt verwijderen?`)) return;
    try {
      const res = await fetch(`/api/blog/${post.id}`, { method: 'DELETE' });
      if (!res.ok) throw new Error('Failed to delete post');
      await fetchPosts();
    } catch (err: any) {
      alert(err.message);
    }
  }

  if (loading) return <p style={{ color: '#787890' }}>Laden...</p>;
  if (error) return <p style={{ color: '#ff6b6b' }}>{error}</p>;

  return (
    <div>
      <div style={styles.header}>
        <span style={styles.count}>{posts.length} post{posts.length !== 1 ? 's' : ''}</span>
        <a href="/admin/blog/new" style={styles.newBtn}>
          + Nieuw artikel
        </a>
      </div>

      {posts.length === 0 ? (
        <div style={styles.empty}>
          <p>Nog geen blogposts. Maak je eerste aan!</p>
        </div>
      ) : (
        <table style={styles.table}>
          <thead>
            <tr>
              <th style={styles.th}>Titel</th>
              <th style={styles.th}>Locale</th>
              <th style={styles.th}>Status</th>
              <th style={styles.th}>Datum</th>
              <th style={styles.thRight}>Acties</th>
            </tr>
          </thead>
          <tbody>
            {posts.map(post => (
              <tr key={post.id} style={styles.tr}>
                <td style={styles.td}>
                  <span style={styles.titleText}>{post.title}</span>
                  <span style={styles.slug}>/{post.slug}</span>
                </td>
                <td style={styles.td}>
                  <span style={styles.locale}>{post.locale.toUpperCase()}</span>
                </td>
                <td style={styles.td}>
                  <span style={post.published ? styles.published : styles.draft}>
                    {post.published ? 'Gepubliceerd' : 'Concept'}
                  </span>
                </td>
                <td style={styles.td}>
                  <span style={styles.date}>
                    {new Date(post.publishedAt || post.createdAt).toLocaleDateString('nl-NL', {
                      year: 'numeric', month: 'short', day: 'numeric',
                    })}
                  </span>
                </td>
                <td style={{ ...styles.td, textAlign: 'right' as const }}>
                  <div style={styles.actions}>
                    <a href={`/admin/blog/${post.id}/edit`} style={styles.actionBtn}>Bewerken</a>
                    <button onClick={() => togglePublish(post)} style={styles.actionBtn}>
                      {post.published ? 'Depubliceren' : 'Publiceren'}
                    </button>
                    <button onClick={() => deletePost(post)} style={styles.deleteBtn}>Verwijderen</button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  count: {
    fontSize: '0.85rem',
    color: '#787890',
  },
  newBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 16px',
    background: '#00d4aa',
    color: '#030306',
    fontWeight: 600,
    fontSize: '0.85rem',
    borderRadius: 6,
    textDecoration: 'none',
  },
  empty: {
    textAlign: 'center' as const,
    padding: '60px 0',
    color: '#787890',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
  },
  th: {
    textAlign: 'left' as const,
    padding: '10px 12px',
    fontSize: '0.75rem',
    fontWeight: 600,
    color: '#787890',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    borderBottom: '1px solid rgba(255, 255, 255, 0.06)',
  },
  thRight: {
    textAlign: 'right' as const,
    padding: '10px 12px',
    fontSize: '0.75rem',
    fontWeight: 600,
    color: '#787890',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    borderBottom: '1px solid rgba(255, 255, 255, 0.06)',
  },
  tr: {
    borderBottom: '1px solid rgba(255, 255, 255, 0.04)',
  },
  td: {
    padding: '14px 12px',
    fontSize: '0.9rem',
    verticalAlign: 'middle' as const,
  },
  titleText: {
    display: 'block',
    fontWeight: 500,
    color: '#f4f4f6',
  },
  slug: {
    display: 'block',
    fontSize: '0.75rem',
    color: '#787890',
    marginTop: 2,
  },
  locale: {
    fontSize: '0.75rem',
    fontWeight: 600,
    padding: '2px 6px',
    background: 'rgba(255, 255, 255, 0.06)',
    borderRadius: 4,
    color: '#b4b4c0',
  },
  published: {
    fontSize: '0.8rem',
    fontWeight: 500,
    color: '#00d4aa',
  },
  draft: {
    fontSize: '0.8rem',
    fontWeight: 500,
    color: '#787890',
  },
  date: {
    fontSize: '0.85rem',
    color: '#b4b4c0',
  },
  actions: {
    display: 'flex',
    gap: 8,
    justifyContent: 'flex-end',
  },
  actionBtn: {
    padding: '5px 10px',
    fontSize: '0.8rem',
    background: 'rgba(255, 255, 255, 0.04)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: 4,
    color: '#b4b4c0',
    cursor: 'pointer',
    textDecoration: 'none',
  },
  deleteBtn: {
    padding: '5px 10px',
    fontSize: '0.8rem',
    background: 'rgba(255, 59, 48, 0.08)',
    border: '1px solid rgba(255, 59, 48, 0.15)',
    borderRadius: 4,
    color: '#ff6b6b',
    cursor: 'pointer',
  },
};
